"""Tests for the SQL fallback path in LLMRouter — Week 5."""
import pytest
from unittest.mock import AsyncMock, MagicMock

from app.services.llm.base import LLMResponse
from app.services.llm_router import LLMRouter
from app.auth.schemas import CurrentUser


@pytest.fixture
def mock_provider():
    provider = AsyncMock()
    provider.name = "mock"
    provider.generate_with_tools.return_value = LLMResponse(
        tool_call=None,
        raw_text="Em chưa hiểu.",
        finish_reason="no_match",
    )
    return provider


@pytest.fixture
def mock_db():
    db = AsyncMock()
    db.execute = AsyncMock()
    db.commit = AsyncMock()
    return db


@pytest.fixture
def manager():
    return CurrentUser(user_id=1, username="hr_manager", role="HR_Manager", dept_id=1)


@pytest.mark.asyncio
async def test_sql_fallback_called_on_no_match(mock_provider, mock_db, manager):
    """When no tool matches, generate_sql must be called."""
    mock_provider.generate_sql = AsyncMock(return_value=None)
    router = LLMRouter(mock_provider)
    await router.route("Câu hỏi không match tool nào", manager, mock_db)
    mock_provider.generate_sql.assert_awaited_once()


@pytest.mark.asyncio
async def test_sql_fallback_returns_sql_mode(mock_provider, mock_db, manager):
    """Successful SQL fallback returns mode='sql'."""
    mock_provider.generate_sql = AsyncMock(
        return_value="SELECT full_name FROM v_employee_safe LIMIT 10"
    )
    mock_provider.summarize = AsyncMock(return_value="Tìm thấy kết quả.")
    fake_result = MagicMock()
    fake_result.keys.return_value = ["full_name"]
    fake_result.fetchall.return_value = [("Nguyễn Văn A",)]
    mock_db.execute = AsyncMock(return_value=fake_result)

    router = LLMRouter(mock_provider)
    result = await router.route("Ad-hoc question", manager, mock_db)

    assert result["mode"] == "sql"
    assert result["tool"] is None
    assert "sql_generated" in result
    assert result["rows"] == 1


@pytest.mark.asyncio
async def test_sql_fallback_blocks_invalid_sql(mock_provider, mock_db, manager):
    """SQL that fails validation is blocked — mode='sql', data=[]."""
    mock_provider.generate_sql = AsyncMock(
        return_value="SELECT * FROM employees LIMIT 10"  # base table — blocked
    )
    router = LLMRouter(mock_provider)
    result = await router.route("Bad query", manager, mock_db)

    assert result["mode"] == "sql"
    assert result["data"] == []
    assert result["rows"] == 0
    assert "validation_error" in result
    assert "employees" in result["validation_error"]


@pytest.mark.asyncio
async def test_sql_fallback_blocks_dml(mock_provider, mock_db, manager):
    """DML generated by LLM is blocked at validation stage."""
    mock_provider.generate_sql = AsyncMock(
        return_value="DELETE FROM v_employee_safe WHERE id = 1"
    )
    router = LLMRouter(mock_provider)
    result = await router.route("Xóa nhân viên", manager, mock_db)

    assert result["mode"] == "sql"
    assert result["data"] == []
    assert "validation_error" in result


@pytest.mark.asyncio
async def test_sql_fallback_generation_failure_returns_graceful_error(mock_provider, mock_db, manager):
    """If LLM returns None (can't generate), return graceful fallback message."""
    mock_provider.generate_sql = AsyncMock(return_value=None)
    router = LLMRouter(mock_provider)
    result = await router.route("Câu hỏi mà LLM không thể sinh SQL", manager, mock_db)

    assert result["mode"] == "sql"
    assert result["data"] == []
    assert result["rows"] == 0
    assert "answer" in result
